//! List of migrations for the current app.
//!
//! Generated by cot CLI 0.4.0 on 2025-10-30 16:29:35+00:00

pub mod m_0001_initial;
/// The list of migrations for current app.
pub const MIGRATIONS: &[&::cot::db::migrations::SyncDynMigration] = &[
    &m_0001_initial::Migration,
];
