//! List of migrations for the current app.
//!
//! Generated by cot CLI 0.4.0 on 2025-11-06 17:52:18+00:00

pub mod m_0002_auto_20251105_155235;
pub mod m_0001_initial;
pub mod m_0003_auto_20251105_155246;
pub mod m_0004_auto_20251106_175218;
/// The list of migrations for current app.
pub const MIGRATIONS: &[&::cot::db::migrations::SyncDynMigration] = &[
    &m_0002_auto_20251105_155235::Migration,
    &m_0001_initial::Migration,
    &m_0003_auto_20251105_155246::Migration,
    &m_0004_auto_20251106_175218::Migration,
];
