//! Generated by cot CLI 0.4.0 on 2025-10-16 14:19:10+00:00

#[derive(Debug, Copy, Clone)]
pub(super) struct Migration;
impl ::cot::db::migrations::Migration for Migration {
    const APP_NAME: &'static str = "main_app";
    const MIGRATION_NAME: &'static str = "m_0001_initial";
    const DEPENDENCIES: &'static [::cot::db::migrations::MigrationDependency] = &[];
    const OPERATIONS: &'static [::cot::db::migrations::Operation] = &[
        ::cot::db::migrations::Operation::create_model()
            .table_name(::cot::db::Identifier::new("main_app__post"))
            .fields(
                &[
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("id"),
                            <cot::db::Auto<i64> as ::cot::db::DatabaseField>::TYPE,
                        )
                        .auto()
                        .primary_key()
                        .set_null(
                            <cot::db::Auto<i64> as ::cot::db::DatabaseField>::NULLABLE,
                        ),
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("name"),
                            <String as ::cot::db::DatabaseField>::TYPE,
                        )
                        .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("description"),
                            <String as ::cot::db::DatabaseField>::TYPE,
                        )
                        .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
                ],
            )
            .build(),
    ];
}

#[derive(::core::fmt::Debug)]
#[::cot::db::model(model_type = "migration")]
struct _Post {
    #[model(primary_key)]
    id: cot::db::Auto<i64>,
    name: String,
    description: String,
}
