//! Generated by cot CLI 0.4.0 on 2025-11-05 15:52:46+00:00

#[derive(Debug, Copy, Clone)]
pub(super) struct Migration;
impl ::cot::db::migrations::Migration for Migration {
    const APP_NAME: &'static str = "main_app";
    const MIGRATION_NAME: &'static str = "m_0003_auto_20251105_155246";
    const DEPENDENCIES: &'static [::cot::db::migrations::MigrationDependency] = &[
        ::cot::db::migrations::MigrationDependency::migration(
            "main_app",
            "m_0002_auto_20251105_155235",
        ),
    ];
    const OPERATIONS: &'static [::cot::db::migrations::Operation] = &[
        ::cot::db::migrations::Operation::remove_field()
            .table_name(::cot::db::Identifier::new("main_app__song"))
            .field(
                ::cot::db::migrations::Field::new(
                        ::cot::db::Identifier::new("youtube_urls"),
                        <String as ::cot::db::DatabaseField>::TYPE,
                    )
                    .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
            )
            .build(),
    ];
}

#[derive(::core::fmt::Debug)]
#[::cot::db::model(model_type = "migration")]
struct _Song {
    #[model(primary_key)]
    pub id: cot::db::Auto<i64>,
    pub youtube_url: String,
}
