//! Generated by cot CLI 0.4.0 on 2025-11-06 17:52:18+00:00

#[derive(Debug, Copy, Clone)]
pub(super) struct Migration;
impl ::cot::db::migrations::Migration for Migration {
    const APP_NAME: &'static str = "main_app";
    const MIGRATION_NAME: &'static str = "m_0004_auto_20251106_175218";
    const DEPENDENCIES: &'static [::cot::db::migrations::MigrationDependency] = &[
        ::cot::db::migrations::MigrationDependency::migration(
            "main_app",
            "m_0003_auto_20251105_155246",
        ),
    ];
    const OPERATIONS: &'static [::cot::db::migrations::Operation] = &[
        ::cot::db::migrations::Operation::create_model()
            .table_name(::cot::db::Identifier::new("main_app__link"))
            .fields(
                &[
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("id"),
                            <cot::db::Auto<i64> as ::cot::db::DatabaseField>::TYPE,
                        )
                        .auto()
                        .primary_key()
                        .set_null(
                            <cot::db::Auto<i64> as ::cot::db::DatabaseField>::NULLABLE,
                        ),
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("url"),
                            <String as ::cot::db::DatabaseField>::TYPE,
                        )
                        .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
                ],
            )
            .build(),
    ];
}

#[derive(::core::fmt::Debug)]
#[::cot::db::model(model_type = "migration")]
struct _Link {
    #[model(primary_key)]
    id: cot::db::Auto<i64>,
    url: String,
}
