//! Generated by cot CLI 0.4.0 on 2025-10-30 16:29:35+00:00

#[derive(Debug, Copy, Clone)]
pub(super) struct Migration;
impl ::cot::db::migrations::Migration for Migration {
    const APP_NAME: &'static str = "main_app";
    const MIGRATION_NAME: &'static str = "m_0001_initial";
    const DEPENDENCIES: &'static [::cot::db::migrations::MigrationDependency] = &[];
    const OPERATIONS: &'static [::cot::db::migrations::Operation] = &[
        ::cot::db::migrations::Operation::create_model()
            .table_name(::cot::db::Identifier::new("main_app__song"))
            .fields(
                &[
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("id"),
                            <cot::db::Auto<i64> as ::cot::db::DatabaseField>::TYPE,
                        )
                        .auto()
                        .primary_key()
                        .set_null(
                            <cot::db::Auto<i64> as ::cot::db::DatabaseField>::NULLABLE,
                        ),
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("youtube_url"),
                            <String as ::cot::db::DatabaseField>::TYPE,
                        )
                        .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
                ],
            )
            .build(),
        ::cot::db::migrations::Operation::create_model()
            .table_name(::cot::db::Identifier::new("main_app__finger_print"))
            .fields(
                &[
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("id"),
                            <cot::db::Auto<i64> as ::cot::db::DatabaseField>::TYPE,
                        )
                        .auto()
                        .primary_key()
                        .set_null(
                            <cot::db::Auto<i64> as ::cot::db::DatabaseField>::NULLABLE,
                        ),
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("address"),
                            <u32 as ::cot::db::DatabaseField>::TYPE,
                        )
                        .set_null(<u32 as ::cot::db::DatabaseField>::NULLABLE),
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("anchor_time_ms"),
                            <u32 as ::cot::db::DatabaseField>::TYPE,
                        )
                        .set_null(<u32 as ::cot::db::DatabaseField>::NULLABLE),
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("song_id"),
                            <i64 as ::cot::db::DatabaseField>::TYPE,
                        )
                        .set_null(<i64 as ::cot::db::DatabaseField>::NULLABLE),
                ],
            )
            .build(),
    ];
}

#[derive(::core::fmt::Debug)]
#[::cot::db::model(model_type = "migration")]
struct _FingerPrint {
    #[model(primary_key)]
    id: cot::db::Auto<i64>,
    address: u32,
    anchor_time_ms: u32,
    song_id: i64,
}
#[derive(::core::fmt::Debug)]
#[::cot::db::model(model_type = "migration")]
struct _Song {
    #[model(primary_key)]
    id: cot::db::Auto<i64>,
    pub youtube_url: String,
}
