secret_key = "ac0d23794286106238abf375ce204ff472acdfa9255fd805adf55f0ef89503e2"

[database]
url = "sqlite://db.sqlite3?mode=rwc"

[auth_backend]
type = "database"

[middlewares]
live_reload.enabled = true

[static_files]
rewrite = "query_param"
cache_timeout = "1year"

[middlewares.session]
secure = false

[middlewares.session.store]
type = "database"
